# Generated by Django 5.2.10 on 2026-01-15 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. AC, Family, Rooftop', max_length=50, unique=True)),
                ('service_charge_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Family section ke liye 10.00 likhein', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Kya yeh section abhi operational hai?')),
                ('display_order', models.IntegerField(default=0, help_text='Dashboard par kounsa section pehle dikhega')),
            ],
            options={
                'verbose_name_plural': 'Table Sections',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('capacity', models.IntegerField(help_text='Kitne log baith sakte hain')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('OUT_OF_ORDER', 'Out of Order')], default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Kya yeh table use karne layak hai?')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.tablesection')),
            ],
            options={
                'ordering': ['table_number'],
            },
        ),
    ]
