# Generated by Django 5.2.10 on 2026-01-15 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Ingredients ya dish ki detail', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_type', models.CharField(choices=[('VEG', 'Veg'), ('NON_VEG', 'Non-Veg'), ('EGG', 'Egg')], default='VEG', max_length=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Kya ye dish aaj kitchen mein hai?')),
                ('prep_time', models.PositiveIntegerField(default=15, help_text='Minutes mein')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='GST %', max_digits=5)),
                ('is_out_of_stock', models.BooleanField(default=False)),
                ('is_special', models.BooleanField(default=False, verbose_name="Chef's Special")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.category')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
